version: '2'
services:
  phpfpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www/html/public
    command: php-fpm -F
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"    
    command: --default-authentication-plugin=mysql_native_password
  apache: 
    build: 
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - 3000:80      
    volumes: 
      - ../:/var/www/html/public
