version: '3'
services:
  phpfpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ../proyectosPHP:/var/www/html/public
      - ../descargas:/descargas
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: php-fpm -F
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"    
    command: --default-authentication-plugin=mysql_native_password
  apache: 
    build: 
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - 3000:80      
    volumes: 
      - ../proyectosPHP:/var/www/html/public
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
